### ISSUE TITLE
一个关于文章排版的问题

### ISSUE THREAD

**Issue by tianheg** [yixiuer/yixiuer.me#25]
在你的文章中，每一个部分的第一段没有缩进两个字符，后面的段落缩进。

我明白你缩进的理由（在你的“关于”页面已经说明），但是第一段不缩进是为什么呢？

我很好奇，期待你的解答

**Comment by yixiuer** [comment]
简单来说，缩进两个字符只是一种分段标识——目的只是为了告诉你这是新的一段。这样明白后，标题后的第一段当然不用多余的缩进。

至于第一段要缩进两个字符的说法也不知到是什么历史原因，反正逻辑上来说，第一段就无需缩进。

会发现一些论文还是严格遵循了逻辑正确的，比如 https://bitcoin.org/bitcoin.pdf

---

- https://www.internetingishard.com/html-and-css/web-typography/#paragraph-indents
- https://io-oi.me/tech/the-philosophy-of-web-typography-text-indent-or-margin/
- https://github.com/reuixiy/hugo-theme-meme/issues/36
