### ISSUE TITLE
将 original 分区重命名为 idea

### ISSUE THREAD

**Issue by yixiuer** [yixiuer/yixiuer.me#26]
很久之前最先尝试按照论文中的概念来分区，所以起名 original，现在看看，再看看其它几个分区，还用 original 莫名奇妙了。

为什么不用 ideas 呢？因为我相信该分区下的文章是真理，而真理是一个整体，不可分割，故没有复数。

**Comment by reuixiy** [comment]
同时需要将 excerpt 重命名为 excerpts。

这样之后，菜单的分类和组成：

1. idea（原创想法）
2. poetry, aphorism（按作品体裁、表达方式、气质）
3. notes, excerpts（评论观点感触和摘录）
4. home, about（首页和关于）

**Comment by reuixiy** [comment]
为保证一如既往的可访问性，使用 Hugo built-in 的 [aliases](https://gohugo.io/content-management/urls/#aliases) 避免重命名后的 404
